services:
  - name: webhook-listener
    env: go
    rootDir: Server
    buildCommand: "go build -o server Server.go"
    startCommand: "./server"
    plan: free
    envVars:
      - key: PORT
        value: "10000"