services:
  - name: webhook-listener
    env: go
    buildCommand: "cd Server && go build -o server Server.go"
    startCommand: "cd Server && ./server"
    plan: free
    envVars:
      - key: PORT
        value: "10000"